{
	"id": "CVE-2021-44420",
	"description": "In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths.\n\nA security issue has been found in Django before version 3.2.10. HTTP requests for URLs with trailing newlines could bypass an upstream access control based on URL paths.",
	"hardware": [],
	"software": [
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-12",
			"version": "< 2:3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-11",
			"version": "< 2:2.2.25-1~deb11u1"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "python-django",
			"platform": "debian-9",
			"version": "< 0"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-12",
			"version": "< 2:3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-11",
			"version": "< 2:2.2.25-1~deb11u1"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "python-django",
			"platform": "debian-9",
			"version": "< 0"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-12",
			"version": "< 2:3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-11",
			"version": "< 2:2.2.25-1~deb11u1"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-12",
			"version": "< 2:3.2.10-1"
		},
		{
			"name": "python-django",
			"platform": "debian-11",
			"version": "< 2:2.2.25-1~deb11u1"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "*"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "< 0"
		}
	],
	"references": [
		"https://www.djangoproject.com/weblog/2021/dec/07/security-releases/",
		"https://github.com/django/django/commit/333c65603032c377e682cdbd7388657a5463a05a",
		"https://groups.google.com/forum/#%21forum/django-announce",
		"https://docs.djangoproject.com/en/3.2/releases/security/",
		"https://www.openwall.com/lists/oss-security/2021/12/07/1",
		"https://security.netapp.com/advisory/ntap-20211229-0006/",
		"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/",
		"https://groups.google.com/forum/#!forum/django-announce",
		"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/B4SQG2EAF4WCI2SLRL6XRDJ3RPK3ZRDV/"
	],
	"severity": "low",
	"state": "published",
	"_is_edited": false
}