{
	"id": "CVE-2013-7338",
	"description": "Python before 3.3.4 RC1 allows remote attackers to cause a denial of service (infinite loop and CPU consumption) via a file size value larger than the size of the zip file to the (1) ZipExtFile.read, (2) ZipExtFile.read(n), (3) ZipExtFile.readlines, (4) ZipFile.extract, or (5) ZipFile.extractall function.",
	"hardware": [],
	"software": [
		{
			"vendor": "debian-bookworm",
			"product": "python2.7",
			"version": "< 0"
		},
		{
			"vendor": "debian-bullseye",
			"product": "python2.7",
			"version": "< 0"
		},
		{
			"vendor": "debian-buster",
			"product": "python2.7",
			"version": "< 0"
		},
		{
			"vendor": "debian-stretch",
			"product": "python2.7",
			"version": "< 0"
		}
	],
	"references": [
		"http://seclists.org/oss-sec/2014/q1/592",
		"http://www.securityfocus.com/bid/65179",
		"http://lists.opensuse.org/opensuse-updates/2014-05/msg00008.html",
		"http://hg.python.org/cpython/rev/79ea4ce431b1",
		"https://security.gentoo.org/glsa/201503-10",
		"http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html",
		"http://bugs.python.org/issue20078",
		"http://seclists.org/oss-sec/2014/q1/595",
		"https://support.apple.com/kb/HT205031",
		"http://www.securitytracker.com/id/1029973",
		"https://docs.python.org/3.3/whatsnew/changelog.html"
	],
	"_edited_": false
}