{
	"id": "CVE-2017-7234",
	"description": "A maliciously crafted URL to a Django site using the serve() view could redirect to any other domain. The view no longer does any redirects as they donâ€™t provide any known, useful functionality.\r\nNote, however, that this view has always carried a warning that it is not hardened for production use and should be used only as a development aid.",
	"hardware": [],
	"software": [
		{
			"name": "python-django",
			"platform": "archlinux",
			"version": "< 1.11-1"
		},
		{
			"name": "python2-django",
			"platform": "archlinux",
			"version": "< 1.11-1"
		},
		{
			"name": "python-django",
			"platform": "debian-8",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.1",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.2",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.3",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-2",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-2.1",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-2.2",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-3",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-3.1",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-4",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-5",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-6",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-7",
			"version": "< 1.7.11-1+deb8u2"
		},
		{
			"name": "python-django",
			"platform": "debian-12",
			"version": "< 1:1.10.7-1"
		},
		{
			"name": "python-django",
			"platform": "debian-11",
			"version": "< 1:1.10.7-1"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "< 1:1.10.7-1"
		}
	],
	"references": [
		"https://docs.djangoproject.com/en/dev/releases/1.11",
		"https://security-tracker.debian.org/tracker/DSA-3835-1"
	],
	"severity": "medium",
	"state": "invalid",
	"is_edited": false
}