{
	"id": "CVE-2013-2099",
	"description": "Algorithmic complexity vulnerability in the ssl.match_hostname function in Python 3.2.x, 3.3.x, and earlier, and unspecified versions of python-backports-ssl_match_hostname as used for older Python versions, allows remote attackers to cause a denial of service (CPU consumption) via multiple wildcard characters in the common name in a certificate.",
	"hardware": [],
	"software": [
		{
			"vendor": "debian-bookworm",
			"product": "bzr",
			"version": "< 2.6.0~bzr6574-1"
		},
		{
			"vendor": "debian-bullseye",
			"product": "bzr",
			"version": "< 2.6.0~bzr6574-1"
		},
		{
			"vendor": "debian-buster",
			"product": "bzr",
			"version": "< 2.6.0~bzr6574-1"
		},
		{
			"vendor": "debian-stretch",
			"product": "bzr",
			"version": "< 2.6.0~bzr6574-1"
		},
		{
			"vendor": "debian-bookworm",
			"product": "linkchecker",
			"version": "< 8.5-1"
		},
		{
			"vendor": "debian-bullseye",
			"product": "linkchecker",
			"version": "< 8.5-1"
		},
		{
			"vendor": "debian-buster",
			"product": "linkchecker",
			"version": "< 8.5-1"
		},
		{
			"vendor": "debian-stretch",
			"product": "linkchecker",
			"version": "< 8.5-1"
		},
		{
			"vendor": "debian-bookworm",
			"product": "python-tornado",
			"version": "< 2.4.1-3"
		},
		{
			"vendor": "debian-bullseye",
			"product": "python-tornado",
			"version": "< 2.4.1-3"
		},
		{
			"vendor": "debian-buster",
			"product": "python-tornado",
			"version": "< 2.4.1-3"
		},
		{
			"vendor": "debian-stretch",
			"product": "python-tornado",
			"version": "< 2.4.1-3"
		},
		{
			"vendor": "debian-bookworm",
			"product": "python-urllib3",
			"version": "< 1.6-2"
		},
		{
			"vendor": "debian-bullseye",
			"product": "python-urllib3",
			"version": "< 1.6-2"
		},
		{
			"vendor": "debian-buster",
			"product": "python-urllib3",
			"version": "< 1.6-2"
		},
		{
			"vendor": "debian-stretch",
			"product": "python-urllib3",
			"version": "< 1.6-2"
		},
		{
			"vendor": "debian-bookworm",
			"product": "python2.7",
			"version": "< 2.7.5-5"
		},
		{
			"vendor": "debian-bullseye",
			"product": "python2.7",
			"version": "< 2.7.5-5"
		},
		{
			"vendor": "debian-buster",
			"product": "python2.7",
			"version": "< 2.7.5-5"
		},
		{
			"vendor": "debian-stretch",
			"product": "python2.7",
			"version": "< 2.7.5-5"
		},
		{
			"vendor": "debian-buster",
			"product": "u1db",
			"version": "< 13.10-1"
		},
		{
			"vendor": "debian-stretch",
			"product": "u1db",
			"version": "< 13.10-1"
		}
	],
	"references": [
		"https://bugzilla.redhat.com/show_bug.cgi?id=963260",
		"http://www.ubuntu.com/usn/USN-1984-1",
		"http://secunia.com/advisories/55116",
		"https://access.redhat.com/errata/RHSA-2016:1166",
		"http://www.ubuntu.com/usn/USN-1985-1",
		"http://bugs.python.org/issue17980",
		"http://secunia.com/advisories/55107",
		"http://rhn.redhat.com/errata/RHSA-2014-1690.html",
		"http://www.ubuntu.com/usn/USN-1983-1",
		"http://www.openwall.com/lists/oss-security/2013/05/16/6"
	],
	"_edited_": false
}