{
	"id": "CVE-2009-3695",
	"description": "",
	"hardware": [],
	"software": [
		{
			"name": "python-django",
			"platform": "debian-5",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.1",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.2",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.3",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-2",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-2.1",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-2.2",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-3",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-3.1",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-4",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-5",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.1",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.2",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-1.3",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-2",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-2.1",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-2.2",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-3",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-3.1",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-4",
			"version": "< 1.0.2-1+lenny2"
		},
		{
			"name": "python-django",
			"platform": "debian-12",
			"version": "< 1.1.1-1"
		},
		{
			"name": "python-django",
			"platform": "debian-11",
			"version": "< 1.1.1-1"
		},
		{
			"name": "python-django",
			"platform": "debian-10",
			"version": "< 1.1.1-1"
		},
		{
			"name": "python-django",
			"platform": "debian-9",
			"version": "< 1.1.1-1"
		}
	],
	"references": [
		"https://security-tracker.debian.org/tracker/DSA-1905-1"
	],
	"severity": null,
	"state": "invalid",
	"_is_edited": false
}