{
	"id": "CVE-2020-13596",
	"description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.\n\nA possible XSS has been found in Django before 3.0.7, via admin ForeignKeyRawIdWidget. Query parameters for the admin ForeignKeyRawIdWidget were not properly URL encoded, posing an XSS attack vector.",
	"hardware": [],
	"software": [
		{
			"vendor": "archlinux",
			"product": "python-django",
			"version": "< 3.0.7-1"
		},
		{
			"vendor": "debian-bookworm",
			"product": "python-django",
			"version": "< 2:2.2.13-1"
		},
		{
			"vendor": "debian-bullseye",
			"product": "python-django",
			"version": "< 2:2.2.13-1"
		},
		{
			"vendor": "debian-buster",
			"product": "python-django",
			"version": "< 1:1.11.29-1~deb10u1"
		},
		{
			"vendor": "debian-stretch",
			"product": "python-django",
			"version": "< 1:1.10.7-2+deb9u9"
		}
	],
	"references": [
		"https://usn.ubuntu.com/4381-1/",
		"https://usn.ubuntu.com/4381-2/",
		"https://www.debian.org/security/2020/dsa-4705",
		"https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
		"https://www.oracle.com/security-alerts/cpujan2021.html",
		"https://docs.djangoproject.com/en/3.0/releases/security/",
		"https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
		"https://security.netapp.com/advisory/ntap-20200611-0002/",
		"https://groups.google.com/forum/#%21msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
		"https://github.com/django/django/commit/1f2dd37f6fcefdd10ed44cb233b2e62b520afb38"
	],
	"_edited_": false,
	"severity": "Medium"
}