{
	"name": "CVE-2021-29611",
	"type": "denial of service",
	"severity": "Low",
	"vector": "Local",
	"description": "A security issue has been found in TensorFlow before version 2.4.2. Incomplete validation in `SparseReshape` results in a denial of service based on a `CHECK`-failure. The implementation(https://github.com/tensorflow/tensorflow/blob/e87b51ce05c3eb172065a6ea5f48415854223285/tensorflow/core/kernels/sparse_reshape_op.cc#L40) has no validation that the input arguments specify a valid sparse tensor.",
	"groups": [
		"AVG-1962"
	],
	"packages": [
		"tensorflow"
	],
	"advisories": [],
	"references": [
		"https://github.com/tensorflow/tensorflow/security/advisories/GHSA-9rpc-5v9q-5r7f",
		"https://github.com/tensorflow/tensorflow/commit/1d04d7d93f4ed3854abf75d6b712d72c3f70d6b6"
	],
	"notes": null
}