{
	"identifier": "CVE-2017-18207",
	"description": "** DISPUTED ** The Wave_read._read_fmt_chunk function in Lib/wave.py in Python through 3.6.4 does not ensure a nonzero channel value, which allows attackers to cause a denial of service (divide-by-zero and exception) via a crafted wav format audio file. NOTE: the vendor disputes this issue because Python applications \"need to be prepared to handle a wide variety of exceptions.\"",
	"type": "network",
	"severity": "medium",
	"state": "disputed",
	"datetime": "2018-03-01T04:29:00Z",
	"is_edited": false,
	"hardware": [],
	"software": [
		{
			"name": "python2",
			"version": "\u003c 0:2.7.18-5.",
			"architecture": "any",
			"manager": "apt",
			"vendor": "mariner-1"
		},
		{
			"name": "python2",
			"version": "\u003c 0:2.7.18-8.",
			"architecture": "any",
			"manager": "apt",
			"vendor": "mariner-2"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-precise"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-trusty"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-artful"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-disco"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-eoan"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-focal"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-impish"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-groovy"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-hirsute"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-jammy"
		},
		{
			"name": "python2.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-kinetic"
		},
		{
			"name": "python3.4",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-trusty"
		},
		{
			"name": "python3.5",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-trusty"
		},
		{
			"name": "python3.5",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-xenial"
		},
		{
			"name": "python3.6",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-artful"
		},
		{
			"name": "python3.6",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python3.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-artful"
		},
		{
			"name": "python3.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-bionic"
		},
		{
			"name": "python3.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-disco"
		},
		{
			"name": "python3.7",
			"version": "any",
			"architecture": "any",
			"manager": "apt",
			"vendor": "ubuntu-eoan"
		}
	],
	"products": [
		{
			"name": "python",
			"version": "\u003c= 3.6.4",
			"architecture": "any",
			"vendor": "python",
			"type": "software",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html",
		"https://bugs.python.org/issue32056",
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18207"
	],
	"weaknesses": [
		"CWE-369"
	]
}