{
	"identifier": "CVE-2021-30005",
	"description": "In JetBrains PyCharm before 2020.3.4, local code execution was possible because of insufficient checks when getting the project from VCS.",
	"type": "local",
	"severity": "medium",
	"state": "published",
	"datetime": "2021-05-11T11:15:07Z",
	"is_edited": false,
	"hardware": [],
	"software": [],
	"products": [
		{
			"name": "pycharm",
			"version": "\u003c 2020.3.4",
			"architecture": "any",
			"vendor": "jetbrains",
			"type": "software",
			"is_edited": false,
			"aliases": []
		}
	],
	"references": [
		"https://blog.jetbrains.com",
		"https://blog.jetbrains.com/blog/2021/05/07/jetbrains-security-bulletin-q1-2021/",
		"https://security.gentoo.org/glsa/202107-45"
	],
	"weaknesses": [
		"CWE-345"
	]
}